title:              A blog, perhaps
email:              your-email@example.com
description:        Ramblings of a deplorable
author:             Erisred
baseurl:            "/blog"
url:                "https://erisred.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    Erisred
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# (remove this comment and the hash at the beginning if used) google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
